add logs for ci-cd.yml into wait api steps; switch inner and outer port in backend-service

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,13 +34,16 @@ jobs:
       - name: Wait for API to be ready
         run: |
           for i in {1..30}; do
-            if curl -s http://localhost:8080/api/getAll; then
-              echo "API is up"
-              break
+            echo "Attempt $i: checking API..."
+            if curl -s --fail http://localhost:8080/api/getAll > /dev/null; then
+              echo "✅ API is up!"
+              exit 0
             fi
-            echo "Waiting for API..."
-            sleep 2
+            sleep 3
           done
+          echo "❌ API failed to start in time"
+          docker compose logs
+          exit 1
       
       - run: |
           python -m pip install --upgrade pip
